version: "3.8"

networks:
    db-net:
    net:

services:
    db:
        build:
            context: postgres
            dockerfile: Dockerfile
        container_name: marketweb-postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - db-net

    api:
        container_name: marketweb-api
        build:
            context: marketweb-api
            dockerfile: Dockerfile
        volumes:
            - ./marketweb-api:/marketweb-api
            - node_modules:/marketweb-api/node_modules
        networks:
            - net
            - db-net
        depends_on:
            - db

    frontend:
        container_name: marketweb-frontend
        build:
            context: marketweb-frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./marketweb-frontend:/marketweb-frontend
            - node_modules_frontend:/marketweb-frontend/node_modules
        networks:
            - net

    nginx:
        container_name: marketweb-nginx
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - net
        depends_on:
            - api
            - frontend

volumes:
    db_data:
    node_modules:
    node_modules_frontend: